language: "gu"
pipeline:
  # this is using the spacy sklearn pipeline, adding duckling
  # all components will use their default values
  # - name: SpacyNLP
  #   model: gu_model
  # - name: SpacyTokenizer
  # - name: SpacyFeaturizer
  # - name: RegexFeaturizer
  # - name: LexicalSyntacticFeaturizer
  # - name: CRFEntityExtractor
  # - name: EntitySynonymMapper
  # - name: SklearnIntentClassifier
  # - name: WhitespaceTokenizer
  # - name: RegexFeaturizer
  # - name: LexicalSyntacticFeaturizer
  # - name: CountVectorsFeaturizer
  # - name: CountVectorsFeaturizer
  #   analyzer: "char_wb"
  #   min_ngram: 1
  #   max_ngram: 4
  # - name: DIETClassifier
  #   epochs: 100
  # - name: EntitySynonymMapper
  # - name: ResponseSelector
  #   epochs: 100
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper   
  - name: CRFEntityExtractor
    "BILOU_flag": True
  - name: RegexEntityExtractor
    # use lookup tables to extract entities
    use_lookup_tables: True
    # use regexes to extract entities
    use_regexes: True
    # use match word boundaries for lookup table
    "use_word_boundaries": False
  - name: FallbackClassifier
    threshold: 0.45
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
    # Confidence threshold for the `core_fallback_action_name` to apply.
    # The action will apply if no other action was predicted with
    # a confidence >= core_fallback_threshold
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
