from typing import List

import yaml
import requests
from pathlib import Path

def getNames(input, value = None):
    base_path = Path(__file__).parent
    file_path = (base_path / "../data/nlu.yml").resolve()
    with open(file_path, "r", encoding="utf-8") as f:
        doc = yaml.load(f, Loader=yaml.FullLoader)
        length = len(doc['nlu'])
        # print(doc['nlu'])
    data = []
    if input == 'plant_names':
        if value == None:
            plant_names = doc['nlu'][length-2]['examples']    
            plant_list = plant_names.splitlines()
            # print(plant_list)        
            for x in plant_list:
                # print(x)
                data.append(x.replace('- ', ''))
            # print(data)
        else:            
            body = {                
                'category': value
            }
            result = requests.post(nodeApiUrl+'kisanQuery/getPlantNames',data = body)
            response  = result.json()
            if len(response['data']) != 0:
                data = response['data']
                print(data)            
    elif input == 'plant_problems':
        plant_problems = doc['nlu'][length-1]['examples']
        plant_list = plant_problems.splitlines()
        # print(plant_list)        
        for x in plant_list:
            # print(x)
            data.append(x.replace('- ', ''))
        # print(data)
    elif input == 'plant_categories':
        plant_categories = doc['nlu'][length-3]['examples']
        plant_list = plant_categories.splitlines()
        for x in plant_list:
            # print(x)
            data.append(x.replace('- ', ''))
    elif input == 'commodity_names':
        commodity_names = doc['nlu'][length-4]['examples']
        plant_list = commodity_names.splitlines()
        for x in plant_list:
            # print(x)
            data.append(x.replace('- ', ''))
        
    return data

def getStateNames():
    return ["છત્તીસગઢ",
    "ગુજરાત",
    "હિમાચલ પ્રદેશ",
    "જમ્મુ અને કાશ્મીર",
    "ઝારખંડ",
    "કર્ણાટક",
    "કેરળ",
    "મધ્યપ્રદેશ",
    "મહારાષ્ટ્ર",
    "ઓરિસ્સા",
    "પંજાબ",
    "રાજસ્થાન",
    "તમિળનાડુ",
    "તેલંગાણા",
    "ત્રિપુર",
    "ઉત્તરપ્રદેશ",
    "ઉત્તરાખંડ",
    "પશ્ચિમ બંગાળ"]

nodeApiUrl = 'https://chatapp-node13.herokuapp.com/api/'

marketPriceUrl = "http://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070?api-key=579b464db66ec23bdd000001cdd3946e44ce4aad7209ff7b23ac571b"

stateMap =  {'છત્તીસગઢ': 'Chattisgarh',
            'ગુજરાત': 'Gujarat',
            'હિમાચલ પ્રદેશ': 'Himachal Pradesh',
            'જમ્મુ અને કાશ્મીર': 'Jammu and Kashmir',
            'ઝારખંડ': 'Jharkhand',
            'કર્ણાટક': 'Karnataka',
            'કેરળ': 'Kerala',
            'મધ્યપ્રદેશ': 'Madhya Pradesh',
            'મહારાષ્ટ્ર': 'Maharashtra',
            'ઓરિસ્સાના': 'Odisha',
            'પંજાબ': 'Punjab',
            'રાજસ્થાન': 'Rajasthan',
            'તમિળનાડુ': 'Tamil Nadu',
            'તેલંગાણા': 'Telangana',
            'ત્રિપુરા': 'Tripura',
            'ઉત્તરપ્રદેશ': 'Uttar Pradesh',
            'ઉત્તરાખંડ': 'Uttrakhand',
            'પશ્ચિમ બંગાળ': 'West Bengal'
            }

stateMapInvert = {
  'Chattisgarh': 'છત્તીસગઢ',
  'Gujarat': 'ગુજરાત',
  'Himachal Pradesh': 'હિમાચલ પ્રદેશ',
  'Jammu and Kashmir': 'જમ્મુ અને કાશ્મીર',
  'Jharkhand': 'ઝારખંડ',
  'Karnataka': 'કર્ણાટક',
  'Kerala': 'કેરળ',
  'Madhya Pradesh': 'મધ્યપ્રદેશ',
  'Maharashtra': 'મહારાષ્ટ્ર',
  'Odisha': 'ઓરિસ્સાના',
  'Punjab': 'પંજાબ',
  'Rajasthan': 'રાજસ્થાન',
  'Tamil Nadu': 'તમિળનાડુ',
  'Telangana': 'તેલંગાણા',
  'Tripura': 'ત્રિપુરા',
  'Uttar Pradesh': 'ઉત્તરપ્રદેશ',
  'Uttrakhand': 'ઉત્તરાખંડ',
  'West Bengal': 'પશ્ચિમ બંગાળ'
}            

districtMapInvert =  {
  'Balrampur': 'બલરામપુર',
  'Kanker': 'કાંકેર',
  'Narayanpur': 'નારાયણપુર',
  'Surajpur': 'સૂરજપુર',
  'Ahmedabad': 'અમદાવાદ',
  'Amreli': 'અમરેલી',
  'Anand': 'આણંદ',
  'Banaskanth': 'બનાસકાંઠા',
  'Bharuch': 'ભરૂચ',
  'Dahod': 'દાહોદ',
  'Gandhinagar': 'ગાંધીનગર',
  'Mehsana': 'મહેસાણા',
  'Morbi': 'મોરબી',
  'Narmada': 'નર્મદા',
  'Patan': 'પાટણમાં',
  'Rajkot': 'રાજકોટ',
  'Sabarkantha': 'સાબરકાંઠા',
  'Surat': 'સુરત',
  'Surendranagar': 'સુરેન્દ્રનગર',
  'Vadodara(Baroda)': 'વડોદરા (બરોડા)',
  'Kullu': 'કુલ્લુ',
  'Solan': 'સોલન',
  'Una': 'ઉના',
  'Anantnag': 'અનંતનાગ',
  'Jammu': 'જમ્મુ',
  'Kathua': 'કઠુઆ',
  'Udhampur': 'ઉધમપૂર',
  'Lohardaga': 'લોહરદગા',
  'Bangalore': 'બેંગલોર',
  'Kolar': 'કોલર',
  'Alappuzha': 'અલાપુઝા',
  'Kannur': 'કન્નુર',
  'Kollam': 'કોલ્લમ',
  'Kottayam': 'કોટ્ટાયમ',
  'Kozhikode(Calicut)': 'કોઝિકોડ (કાલિકટ)',
  'Malappuram': 'માલાપ્પુરામ',
  'Pathanamthitta': 'પઠાનમથિત્ત​',
  'Thirssur': 'થ્રિસુર',
  'Wayanad': 'વયનદ',
  'Alirajpur': 'અલીરાજપુર',
  'Badwani': 'બદવાની',
  'Balaghat': 'બાલાઘાટ',
  'Dindori': 'ડિંડોરી',
  'Raisen': 'રાયસેન',
  'Ratlam': 'રતલામ',
  'Shivpuri': 'શિવપુરી',
  'Vidisha': 'વિદિશા',
  'Ahmednagar': 'અહમદનગર',
  'Amarawati': 'અમરાવતી',
  'Jalgaon': 'જલગાંવ',
  'Nashik': 'નાસિક',
  'Pune': 'પુણે',
  'Satara': 'સતારા',
  'Sholapur': 'સોલાપુર',
  'Bargarh': 'બારગઢ',
  'Cuttack': 'કટક',
  'Dhenkanal': 'ધેનકાનાલ',
  'Gajapati': 'ગજપતિ',
  'Koraput': 'કોરાપુટ',
  'Mayurbhanja': 'મયુરભાંજા',
  'Rayagada': 'રાયગડા',
  'Amritsar': 'અમૃતસર',
  'Bhatinda': 'ભટીંડા',
  'Ferozpur': 'ફિરોજપુર',
  'Gurdaspur': 'ગુરદાસપુર',
  'Jalandhar': 'જલંધર',
  'Ludhiana': 'લુધિયાણા',
  'Sangrur': 'સંગરૂર',
  'Tarntaran': 'તરતરન',
  'Dausa': 'દૌસા',
  'Hanumangarh': 'હનુમાનગઢ',
  'Jalore': 'જલોર',
  'Jodhpur': 'જોધપુર',
  'Swai Madhopur': 'સવાઈ માધોપુર',
  'Udaipur': 'ઉદયપુર',
  'Coimbatore': 'કોઈમ્બતુર',
  'Erode': 'ઇરોડ',
  'Madurai': 'મદુરાઈ',
  'Villupuram': 'વિલ્લુપુરમ',
  'Nalgonda': 'નાલગોંડા',
  'Nizamabad': 'નિઝામાબાદ',
  'Warangal': 'વારંગલના',
  'South District': 'દક્ષિણ જિલ્લાનું',
  'Agra': 'આગરા',
  'Auraiya': 'ઉરૈયા',
  'Badaun': 'બડાઉન',
  'Baghpat': 'બાગપત',
  'Bareilly': 'બરેલી',
  'Bhadohi(Sant Ravi Nagar)': 'ભદોહી (સંત રવિ નગર)',
  'Bijnor': 'બિજનૌર',
  'Firozabad': 'ફિરોઝાબાદથી',
  'Hamirpur': 'હમીરપુર',
  'Jalaun (Orai)': 'જલાઉન (ઓરઇ)',
  'Jhansi': 'ઝાંસી',
  'Maharajganj': 'મહારાજગંજ',
  'Mainpuri': 'મૈનપુરી',
  'Muradabad': 'મુરાદાબાદ',
  'Muzaffarnagar': 'મુઝફ્ફરનગર',
  'Padrauna(Kusinagar)': 'પાદરાઉના (કુસીનગર)',
  'Saharanpur': 'સહરાનપુર',
  'Shahjahanpur': 'શાહજહાંપુર',
  'Siddharth Nagar': 'સિદ્ધાર્થ નગર',
  'Dehradoon': 'દેહરાદૂન',
  'Nanital': 'નૈનીતાલ',
  'Bankura': 'બંકુરા',
  'Burdwan': 'બર્દવાન',
  'Darjeeling': 'દાર્જિલિંગ'
}

commodityMap = {
    'ડાંગર (ધન) (સામાન્ય)': 'Paddy(Dhan)(Common)',
    'મકાઈ': 'Maize',
    'કપાસ': 'Cotton',
    'અરહર (તૂર / લાલ ગ્રામ) (સંપૂર્ણ)': 'Arhar (Tur/Red Gram)(Whole)',
    'ઘઉં': 'Wheat',
    'ભીંડી (લેડીઝ ફિંગર)': 'Bhindi(Ladies Finger)',
    'બ્રિંજલ': 'Brinjal',
    'કોબી': 'Cabbage',
    'કોબીજ': 'Cauliflower',
    'ધાણા (પાંદડા)': 'Coriander(Leaves)',
    'આદુ (લીલો)': 'Ginger(Green)',
    'લીલો મરચું': 'Green Chilli',
    'ગવાર': 'Guar',
    'લીંબુ': 'Lemon',
    'બાજરા (મોતીની બાજરી / કમ્બૂ)': 'Bajra(Pearl Millet/Cumbu)',
    'કાળો ગ્રામ (ઉર્દ દાળો) (સંપૂર્ણ)': 'Black Gram (Urd Beans)(Whole)',
    'મગફળી': 'Groundnut',
    'જુવાર (જુવાર)': 'Jowar(Sorghum)',
    'કાબૂલી ચણા (ચણા-સફેદ)': 'Kabuli Chana(Chickpeas-White)',
    'રાજગીર': 'Rajgir',
    'તલ (તલ, ગિંજલી, તિલ)': 'Sesamum(Sesame,Gingelly,Til)',
    'બંગાળ ગ્રામ (ગ્રામ) (સંપૂર્ણ)': 'Bengal Gram(Gram)(Whole)',
    'એરંડા બીજ': 'Castor Seed',
    'કમિન બીજ (જીરા)': 'Cummin Seed(Jeera)',
    'દુધી': 'Bottle gourd',
    'ગાજર': 'Carrot',
    'ડુંગળી': 'Onion',
    'બટાટા': 'Potato',
    'ટામેટા': 'Tomato',
    'ગવાર બીજ (ક્લસ્ટર બીજ)': 'Guar Seed(Cluster Beans Seed)',
    'સરસવ': 'Mustard',
    'મેથી (પાંદડા)': 'Methi(Leaves)',
    'ડુંગળી લીલો': 'Onion Green',
    'સુરત કઠોળ (પાપડી)': 'Surat Beans (Papadi)',
    'કેળા': 'Banana',
    'કોરિએન્ડર બીજ': 'Corriander seed',
    'સોયાબિન': 'Soyabean',
    'લસણ': 'Garlic',
    'લીલો ગ્રામ (મૂંગ) (સંપૂર્ણ)': 'Green Gram (Moong)(Whole)',
    'ગ્રાઉન્ડ બદામ બીજ': 'Ground Nut Seed',
    'મેથી સીડ્સ': 'Methi Seeds',
    'ક્લસ્ટર કઠોળ': 'Cluster beans',
    'બીટનો કંદ': 'Beetroot',
    'કડવો લોટ': 'Bitter gourd',
    'કાઉપિયા (વેજ)': 'Cowpea(Veg)',
    'કુકુમ્બર (ખીરા)': 'Cucumbar(Kheera)',
    'ડ્રમસ્ટિક': 'Drumstick',
    'હાથી યમ (સુરન)': 'Elephant Yam (Suran)',
    'ફ્રેન્ચ કઠોળ (ફ્રાસિયન)': 'French Beans (Frasbean)',
    'ભારતીય કઠોળ (સીમ)': 'Indian Beans (Seam)',
    'નાનો લોટ (કુંદરૂ)': 'Little gourd (Kundru)',
    'પીગન પેં (અરહર ફાલી)': 'Pegeon Pea (Arhar Fali)',
    'પોઇંટેડ લોટ (પરવલ)': 'Pointed gourd (Parval)',
    'કોળુ': 'Pumpkin',
    'રીજ લોટ (ટોરી)': 'Ridge gourd(Tori)',
    'શક્કરિયા': 'Sweet Potato',
    'હળદર (કાચી)': 'Turmeric (raw)',
    'યમ (રતલુ)': 'Yam (Ratalu)',
    'કુલ્થી (ઘોડો ગ્રામ)': 'Kulthi(Horse Gram)',
    'સોનફ': 'Soanf',
    'આમલા (નેલી કાઈ)': 'Amla(Nelli Kai)',
    'કેળા - લીલોતરી': 'Banana - Green',
    'પપૈયા (કાચો)': 'Papaya (Raw)',
    'વટાણાની ભીની': 'Peas Wet',
    'મૂળાની': 'Raddish',
    'પાલક': 'Spinach',
    'ટીંડા': 'Tinda',
    'કેપ્સિકમ': 'Capsicum',
    'ચિકૂઝ (સપોટા)': 'Chikoos(Sapota)',
    'કોલાકેસીયા': 'Colacasia',
    'દ્રાક્ષ': 'Grapes',
    'જામફળ': 'Guava',
    'કિન્નુ': 'Kinnow',
    'મૌસામ્બી (મીઠી ચૂનો)': 'Mousambi(Sweet Lime)',
    'નારંગી': 'Orange',
    'પપૈયા': 'Papaya',
    'સ્ક્વોશ (ચપ્પલ કડુ)': 'Squash(Chappal Kadoo)',
    'એપલ': 'Apple',
    'મશરૂમ્સ': 'Mashrooms',
    'વટાણાની કodડ': 'Peas cod',
    'દાડમ': 'Pomegranate',
    'સલગમ': 'Turnip',
    'નૂલ ખોલ': 'Knool Khol',
    'ડાલડા': 'Dalda',
    'મહુઆ': 'Mahua',
    'સરસવનું તેલ': 'Mustard Oil',
    'ભાત': 'Rice',
    'ખાંડ': 'Sugar',
    'ઘઉં આટ્ટા': 'Wheat Atta',
    'સફેદ વટાણા': 'White Peas',
    'કઠોળ': 'Beans',
    'મરચું કેપ્સિકમ': 'Chilly Capsicum',
    'લીલો અવેર (ડબલ્યુ)': 'Green Avare (W)',
    'સીમેબદનેકાય': 'Seemebadnekai',
    'સાપની લોટ': 'Snake gourd',
    'સુવર્ણ ગડ્ડે': 'Suvarna Gadde',
    'મીઠો કોળુ': 'Sweet Pumpkin',
    'થોન્ડેકાય': 'Thondekai',
    'એમ્ફોફાલસ': 'Amphophalus',
    'એશગourર્ડ': 'Ashgourd',
    'અમરાન્થુસ': 'Amaranthus',
    'કેરી': 'Mango',
    'અનેનાસ': 'Pineapple',
    'ટેપિઓકા': 'Tapioca',
    'કાળા મરી': 'Black pepper',
    'નાળિયેર તેલ': 'Coconut Oil',
    'નાળિયેર': 'Coconut',
    'કેરી (કાચો-પાક)': 'Mango (Raw-Ripe)',
    'મરી ungarbled': 'Pepper ungarbled',
    'કોફી': 'Coffee',
    'રબર': 'Rubber',
    'દાળ (મસુર) (સંપૂર્ણ)': 'Lentil (Masur)(Whole)',
    'કરબુજા (કસ્તુરી તરબૂચ)': 'Karbuja(Musk Melon)',
    'ચૂનો': 'Lime',
    'આમલી ફળ': 'Tamarind Fruit',
    'તરબૂચ': 'Water Melon',
    'લીલા વટાણા': 'Green Peas',
    'રાગી (ફિંગર બાજરી)': 'Ragi (Finger Millet)',
    'ટંકશાળ (પુડીના)': 'Mint(Pudina)',
    'માછલી': 'Fish',
    'ઉંદર પૂંછડી મૂળા (મોગારી)': 'Rat Tail Radish (Mogari)',
    'ક્ષેત્ર વટાણા': 'Field Pea',
    'જવ (જૌ)': 'Barley (Jau)',
    'કોપરા': 'Copra',
    'ટીવી કમ્બૂ': 'T.V. Cumbu',
    'ગુર (ગોળ)': 'Gur(Jaggery)',
    'ડાંગર (ધન) (બાસમતી)': 'Paddy(Dhan)(Basmati)',
    'જેક ફળ': 'Jack Fruit',
    'વટાણા (સુકા)': 'Peas(Dry)'
}

commodityMapInvert = {
  'Paddy(Dhan)(Common)': 'ડાંગર (ધન) (સામાન્ય)',
  'Maize': 'મકાઈ',
  'Cotton': 'કપાસ',
  'Arhar (Tur/Red Gram)(Whole)': 'અરહર (તૂર / લાલ ગ્રામ) (સંપૂર્ણ)',
  'Wheat': 'ઘઉં',
  'Bhindi(Ladies Finger)': 'ભીંડી (લેડીઝ ફિંગર)',
  'Brinjal': 'બ્રિંજલ',
  'Cabbage': 'કોબી',
  'Cauliflower': 'કોબીજ',
  'Coriander(Leaves)': 'ધાણા (પાંદડા)',
  'Ginger(Green)': 'આદુ (લીલો)',
  'Green Chilli': 'લીલો મરચું',
  'Guar': 'ગવાર',
  'Lemon': 'લીંબુ',
  'Bajra(Pearl Millet/Cumbu)': 'બાજરા (મોતીની બાજરી / કમ્બૂ)',
  'Black Gram (Urd Beans)(Whole)': 'કાળો ગ્રામ (ઉર્દ દાળો) (સંપૂર્ણ)',
  'Groundnut': 'મગફળી',
  'Jowar(Sorghum)': 'જુવાર (જુવાર)',
  'Kabuli Chana(Chickpeas-White)': 'કાબૂલી ચણા (ચણા-સફેદ)',
  'Rajgir': 'રાજગીર',
  'Sesamum(Sesame,Gingelly,Til)': 'તલ (તલ, ગિંજલી, તિલ)',
  'Bengal Gram(Gram)(Whole)': 'બંગાળ ગ્રામ (ગ્રામ) (સંપૂર્ણ)',
  'Castor Seed': 'એરંડા બીજ',
  'Cummin Seed(Jeera)': 'કમિન બીજ (જીરા)',
  'Bottle gourd': 'બોટલ લ.',
  'Carrot': 'ગાજર',
  'Onion': 'ડુંગળી',
  'Potato': 'બટાટા',
  'Tomato': 'ટામેટા',
  'Guar Seed(Cluster Beans Seed)': 'ગવાર બીજ (ક્લસ્ટર બીજ)',
  'Mustard': 'સરસવ',
  'Methi(Leaves)': 'મેથી (પાંદડા)',
  'Onion Green': 'ડુંગળી લીલો',
  'Surat Beans (Papadi)': 'સુરત કઠોળ (પાપડી)',
  'Banana': 'કેળા',
  'Corriander seed': 'કોરિએન્ડર બીજ',
  'Soyabean': 'સોયાબિન',
  'Garlic': 'લસણ',
  'Green Gram (Moong)(Whole)': 'લીલો ગ્રામ (મૂંગ) (સંપૂર્ણ)',
  'Ground Nut Seed': 'ગ્રાઉન્ડ બદામ બીજ',
  'Methi Seeds': 'મેથી સીડ્સ',
  'Cluster beans': 'ક્લસ્ટર કઠોળ',
  'Beetroot': 'બીટનો કંદ',
  'Bitter gourd': 'કડવો લોટ',
  'Cowpea(Veg)': 'કાઉપિયા (વેજ)',
  'Cucumbar(Kheera)': 'કુકુમ્બર (ખીરા)',
  'Drumstick': 'ડ્રમસ્ટિક',
  'Elephant Yam (Suran)': 'હાથી યમ (સુરન)',
  'French Beans (Frasbean)': 'ફ્રેન્ચ કઠોળ (ફ્રાસિયન)',
  'Indian Beans (Seam)': 'ભારતીય કઠોળ (સીમ)',
  'Little gourd (Kundru)': 'નાનો લોટ (કુંદરૂ)',
  'Pegeon Pea (Arhar Fali)': 'પીગન પેં (અરહર ફાલી)',
  'Pointed gourd (Parval)': 'પોઇંટેડ લોટ (પરવલ)',
  'Pumpkin': 'કોળુ',
  'Ridge gourd(Tori)': 'રીજ લોટ (ટોરી)',
  'Sweet Potato': 'શક્કરિયા',
  'Turmeric (raw)': 'હળદર (કાચી)',
  'Yam (Ratalu)': 'યમ (રતલુ)',
  'Kulthi(Horse Gram)': 'કુલ્થી (ઘોડો ગ્રામ)',
  'Soanf': 'સોનફ',
  'Amla(Nelli Kai)': 'આમલા (નેલી કાઈ)',
  'Banana - Green': 'કેળા - લીલોતરી',
  'Papaya (Raw)': 'પપૈયા (કાચો)',
  'Peas Wet': 'વટાણાની ભીની',
  'Raddish': 'મૂળાની',
  'Spinach': 'પાલક',
  'Tinda': 'ટીંડા',
  'Capsicum': 'કેપ્સિકમ',
  'Chikoos(Sapota)': 'ચિકૂઝ (સપોટા)',
  'Colacasia': 'કોલાકેસીયા',
  'Grapes': 'દ્રાક્ષ',
  'Guava': 'જામફળ',
  'Kinnow': 'કિન્નુ',
  'Mousambi(Sweet Lime)': 'મૌસામ્બી (મીઠી ચૂનો)',
  'Orange': 'નારંગી',
  'Papaya': 'પપૈયા',
  'Squash(Chappal Kadoo)': 'સ્ક્વોશ (ચપ્પલ કડુ)',
  'Apple': 'એપલ',
  'Mashrooms': 'મશરૂમ્સ',
  'Peas cod': 'વટાણાની કodડ',
  'Pomegranate': 'દાડમ',
  'Turnip': 'સલગમ',
  'Knool Khol': 'નૂલ ખોલ',
  'Dalda': 'ડાલડા',
  'Mahua': 'મહુઆ',
  'Mustard Oil': 'સરસવનું તેલ',
  'Rice': 'ભાત',
  'Sugar': 'ખાંડ',
  'Wheat Atta': 'ઘઉં આટ્ટા',
  'White Peas': 'સફેદ વટાણા',
  'Beans': 'કઠોળ',
  'Chilly Capsicum': 'મરચું કેપ્સિકમ',
  'Green Avare (W)': 'લીલો અવેર (ડબલ્યુ)',
  'Seemebadnekai': 'સીમેબદનેકાય',
  'Snake gourd': 'સાપની લોટ',
  'Suvarna Gadde': 'સુવર્ણ ગડ્ડે',
  'Sweet Pumpkin': 'મીઠો કોળુ',
  'Thondekai': 'થોન્ડેકાય',
  'Amphophalus': 'એમ્ફોફાલસ',
  'Ashgourd': 'એશગourર્ડ',
  'Amaranthus': 'અમરાન્થુસ',
  'Mango': 'કેરી',
  'Pineapple': 'અનેનાસ',
  'Tapioca': 'ટેપિઓકા',
  'Black pepper': 'કાળા મરી',
  'Coconut Oil': 'નાળિયેર તેલ',
  'Coconut': 'નાળિયેર',
  'Mango (Raw-Ripe)': 'કેરી (કાચો-પાક)',
  'Pepper ungarbled': 'મરી ungarbled',
  'Coffee': 'કોફી',
  'Rubber': 'રબર',
  'Lentil (Masur)(Whole)': 'દાળ (મસુર) (સંપૂર્ણ)',
  'Karbuja(Musk Melon)': 'કરબુજા (કસ્તુરી તરબૂચ)',
  'Lime': 'ચૂનો',
  'Tamarind Fruit': 'આમલી ફળ',
  'Water Melon': 'તરબૂચ',
  'Green Peas': 'લીલા વટાણા',
  'Ragi (Finger Millet)': 'રાગી (ફિંગર બાજરી)',
  'Mint(Pudina)': 'ટંકશાળ (પુડીના)',
  'Fish': 'માછલી',
  'Rat Tail Radish (Mogari)': 'ઉંદર પૂંછડી મૂળા (મોગારી)',
  'Field Pea': 'ક્ષેત્ર વટાણા',
  'Barley (Jau)': 'જવ (જૌ)',
  'Copra': 'કોપરા',
  'T.V. Cumbu': 'ટીવી કમ્બૂ',
  'Gur(Jaggery)': 'ગુર (ગોળ)',
  'Paddy(Dhan)(Basmati)': 'ડાંગર (ધન) (બાસમતી)',
  'Jack Fruit': 'જેક ફળ',
  'Peas(Dry)': 'વટાણા (સુકા)'
}

varietiesMapInvert = {
  '1001': '1001',
  'Paddy fine': 'ડાંગર બરાબર',
  'MTU-1001': 'એમટીયુ -1001',
  'Other': 'અન્ય',
  'Hybrid/Local': 'વર્ણસંકર / સ્થાનિક',
  'Local': 'સ્થાનિક',
  'Paddy Coarse': 'ડાંગર બરછટ',
  'I.R. 36': 'આઈઆર 36',
  'Shanker 6 (B) 30mm FIne': 'શંકર 6 (બી) 30 મીમી ફાઇન',
  '777 New Ind': '777 નવી ભારત',
  'Lokwan Gujrat': 'લોકવાન ગુજરાત',
  'Bhindi': 'ભીંડી',
  'Cabbage': 'કોબી',
  'Cauliflower': 'કોબીજ',
  'Coriander': 'ધાણા',
  'Green Ginger': 'લીલો આદુ',
  'Green Chilly': 'લીલો મરચું',
  'Gwar': 'ગ્વાર',
  'Lemon': 'લીંબુ',
  'Kabul': 'કાબુલ',
  'Black': 'કાળો',
  'White': 'સફેદ',
  'PISSI': 'પી.એસ.એસ.આઇ.',
  'Small (Whole)': 'નાના (સંપૂર્ણ)',
  'Deshi': 'દેશી',
  'Desi (Whole)': 'દેશી (સંપૂર્ણ)',
  'Black Gram (Whole)': 'કાળો ગ્રામ (સંપૂર્ણ)',
  'Castor seed': 'એરંડા બીજ',
  'Narma BT Cotton': 'નર્મમા બીટી કપાસ',
  'Cummin Seed(Jeera)': 'કમિન બીજ (જીરા)',
  'Big (With Shell)': 'મોટું (શેલ સાથે)',
  'Bold': 'બોલ્ડ',
  'Jowar ( White)': 'જુવાર (સફેદ)',
  'Bansi': 'બંસી',
  'Lokwan': 'લોકવાન',
  'Bottle Gourd': 'બોટલ લોટ',
  'Brinjal': 'બ્રિંજલ',
  'Carrot': 'ગાજર',
  'Onion': 'ડુંગળી',
  'Potato': 'બટાટા',
  'Common': 'સામાન્ય',
  'Round/Long': 'ગોળ / લાંબી',
  'Methi': 'મેથી',
  'Onion Green': 'ડુંગળી લીલો',
  'Cotton (Unginned)': 'કપાસ (ચાલુ ન રાખેલ)',
  'Medium': 'માધ્યમ',
  'Rajkot T-9': 'રાજકોટ ટી -9',
  'Medium Green': 'મધ્યમ લીલો',
  'G20': 'જી 20',
  'Yellow': 'પીળો',
  'Arhar (Whole)': 'અરહર (સંપૂર્ણ)',
  'Desi': 'દેશી',
  'Caster': 'કેસ્ટર',
  'Coriander Seed': 'ધાણા બીજ',
  'Garlic': 'લસણ',
  'Green (Whole)': 'લીલો (સંપૂર્ણ)',
  'Ground Nut Seed': 'ગ્રાઉન્ડ બદામ બીજ',
  'Jowar (Yellow)': 'જુવાર (પીળો)',
  'Red': 'લાલ',
  'Methiseeds': 'પદ્ધતિઓ',
  'Mustard': 'સરસવ',
  'Sharbati': 'શરબતી',
  'Cluster Beans': 'ક્લસ્ટર બીન્સ',
  'Tomato': 'ટામેટા',
  'RCH-2': 'આરસીએચ -2',
  'Horse gram (Whole)': 'ઘોડો ગ્રામ (સંપૂર્ણ)',
  'Amla': 'આમળા',
  'Banana - Green': 'કેળા - લીલોતરી',
  'Cucumbar': 'કુકુમ્બર',
  'Drumstick': 'ડ્રમસ્ટિક',
  'Elephant Yam (Suran)': 'હાથી યમ (સુરન)',
  'French Beans (Frasbean)': 'ફ્રેન્ચ કઠોળ (ફ્રાસિયન)',
  'Papaya (Raw)': 'પપૈયા (કાચો)',
  'Peas Wet': 'વટાણાની ભીની',
  'Raddish': 'મૂળાની',
  'Spinach': 'પાલક',
  'Sweet Potato': 'શક્કરિયા',
  'Tinda': 'ટીંડા',
  'Colacasia': 'કોલાકેસીયા',
  'Apple': 'એપલ',
  'Capsicum': 'કેપ્સિકમ',
  'Green': 'લીલા',
  'Knool Khol': 'નૂલ ખોલ',
  'Hybrid': 'વર્ણસંકર',
  'Delicious': 'સ્વાદિષ્ટ',
  'Kinnow': 'કિન્નુ',
  'Nagpuri': 'નાગપુરી',
  'Turnip': 'સલગમ',
  'Little gourd (Kundru)': 'નાનો લોટ (કુંદરૂ)',
  'Banana - Ripe': 'કેળા - પાકા',
  'Guava Alahabad': 'જામફળ અલાહાબાદ',
  'Dalda': 'ડાલડા',
  'Deshi Red': 'દેશી લાલ',
  'Paddy Medium': 'ડાંગર માધ્યમ',
  'Jyoti': 'જ્યોતિ',
  'Pumpkin': 'કોળુ',
  'Fine': 'સરસ',
  'Chini': 'ચિની',
  'Medium Fine': 'મધ્યમ ફાઇન',
  'Wheat Atta': 'ઘઉં આટ્ટા',
  'White Peas': 'સફેદ વટાણા',
  'Beans (Whole)': 'કઠોળ (સંપૂર્ણ)',
  'Beetroot': 'બીટનો કંદ',
  'Bitter Gourd': 'કડવો લોટલો',
  'Round': 'ગોળ',
  'Chilly Capsicum': 'મરચું કેપ્સિકમ',
  'Green Avare (W)': 'લીલો અવેર (ડબલ્યુ)',
  'Papaya': 'પપૈયા',
  'Ridgeguard(Tori)': 'રીજગાર્ડ (ટોરી)',
  'Seemebadanekai': 'સીમેબદાનેકાય',
  'Snakeguard': 'સ્નેકગાર્ડ',
  'Suvarnagadde': 'સુવર્ણગડ્ડે',
  'Sweet Pumpkin': 'મીઠો કોળુ',
  'Thondekai': 'થોન્ડેકાય',
  'Cowpea (Veg)': 'કાઉપિયા (વેજ)',
  'Small': 'નાનું',
  'Nendra Bale': 'નેન્દ્ર બાલે',
  'Big': 'મોટું',
  'Ashgourd': 'એશગourર્ડ',
  'Poovan': 'પૂવન',
  'Mango - Raw-Ripe': 'કેરી - કાચો-પાકેલો',
  'Tapioca': 'ટેપિઓકા',
  'Palayamthodan': 'પલાયમોડ્થન',
  'Average (Whole)': 'સરેરાશ (સંપૂર્ણ)',
  'Amaranthus': 'અમરાન્થુસ',
  'Amphophalus': 'એમ્ફોફાલસ',
  'Rasakathai': 'રસકથાય',
  'Average': 'સરેરાશ',
  'Masur Dal': 'મસુર દાલ',
  '1st Sort': '1 લી સortર્ટ',
  'MECH-1': 'MECH-1',
  'Sapota': 'સપોટા',
  'Peas cod': 'વટાણાની કodડ',
  '(Red Nanital)': '(લાલ નેનીટલ)',
  'Field Pea': 'ક્ષેત્ર વટાણા',
  'Pomogranate': 'પોમોગ્રાનેટ',
  'American': 'અમેરિકન',
  'Coconut': 'નાળિયેર',
  'Copra': 'કોપરા',
  'Ponni': 'પોની',
  'MCU 5': 'એમસીયુ 5',
  'MTU-1010': 'એમટીયુ -1010',
  'B P T': 'બી.પી.ટી.',
  'African Sarson': 'આફ્રિકન સારસન',
  'Dara': 'દારા',
  'Sarson(Black)': 'સારસન (બ્લેક)',
  'Amruthapani': 'અમૃતપાની',
  'Kasmir/Shimla - II': 'કાસ્મિર / સિમલા - II',
  'Chips': 'ચિપ્સ',
  'Kufri Megha': 'કુફરી મેઘા',
  'Annabesahai': 'અન્નાબેશાય',
  'Sugandha': 'સુગંધા',
  'III': 'III',
  'Mousambi': 'મૌસામ્બી',
  'SuperFine(Basmati)': 'સુપરફાઈન (બાસમતી)',
  'Guava': 'જામફળ',
  'Green Peas': 'લીલા વટાણા',
  'Basmati 1509': 'બાસમતી 1509',
  'Jack Fruit': 'જેક ફળ',
  'Peas(Dry)': 'વટાણા (સુકા)',
  'Swarna Masuri (New)': 'સ્વર્ણા મસુરી (નવું)',
  'Sonalika': 'સોનાલિકા'
}


if __name__ == "__main__":
    print("***")